---
deployment:
  tasks:
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/index.html /home/digi7586/public_html/index.html
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/ornekler.html /home/digi7586/public_html/ornekler.html
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/sitemap.xml /home/digi7586/public_html/sitemap.xml
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/robots.txt /home/digi7586/public_html/robots.txt
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/form-handler.php /home/digi7586/public_html/form-handler.php
    - /bin/mkdir -p /home/digi7586/public_html/assets/css
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/assets/css/form.css /home/digi7586/public_html/assets/css/form.css
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/assets/css/blog.css /home/digi7586/public_html/assets/css/blog.css
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/assets/css/hakkimizda.css /home/digi7586/public_html/assets/css/hakkimizda.css
    - /bin/cp -f /home/digi7586/repositories/digitalbohem-site/hakkimizda.html /home/digi7586/public_html/hakkimizda.html
    - /bin/mkdir -p /home/digi7586/public_html/blog
    - /bin/cp -rf /home/digi7586/repositories/digitalbohem-site/blog/. /home/digi7586/public_html/blog/
