---
deployment:
  tasks:
    - export DEPLOYPATH=/home/digi7586/public_html/
    - /bin/cp -f $REPOSITORY_WEBROOT/index.html $DEPLOYPATH
    - /bin/cp -f $REPOSITORY_WEBROOT/ornekler.html $DEPLOYPATH
    - /bin/cp -f $REPOSITORY_WEBROOT/sitemap.xml $DEPLOYPATH
    - /bin/cp -f $REPOSITORY_WEBROOT/robots.txt $DEPLOYPATH
